### PR TITLE
App level addins config

### PR DESCRIPTION
**Pull request by lukaszunity**
Add support for application level addins-config.xml that can be used to disable add-ins that are shipped with the application.

### CODE REVIEW

**Comment by slluis** [comment]
I'm not sure what are you trying to achieve. Do you want to disable some add-ins by default but still let users enable them if they wish?

**Comment by lukaszunity** [comment]
Yes, because they are no available through the add-in gallery. Like the Git and Subversion add-ins that ship with MonoDevelop.

**Comment by lukaszunity** [comment]
Is there any other possible solution to disabled shipped add-ins by default?

**Comment by slluis** [comment]
Looks good to me

**Pull request merged**
