### PR TITLE
Modernize the solution a bit

### PR DESCRIPTION
**Pull request by mhutch**
It's no longer possible to build or package this correctly with the makefiles, so clean them up. Remove the changelogs too, as they're outdated and the info is in the git logs. Switch NuGet refs to PackageReference and set up NuGetizer to create package automatically for release builds.

### CODE REVIEW

**Comment by slluis** [comment]
This broke the build in VSTS 😞

**Comment by slluis** [comment]
In fact I can't event build Mono.Addins anymore even with latest XS from master.

**Comment by mhutch** [comment]
@slluis what errors do you get?

**Comment by slluis** [comment]
Error: /Users/lluis/prog/work/mono-addins/Mono.Addins/Mono.Addins.csproj: The attribute "Version" in element <PackageReference> is unrecognized. (mautil)

**Comment by mhutch** [comment]
@slluis that sounds like a pre-15.0 MSBuild

**Comment by slluis** [comment]
I have Mono 5.2.0.138

**Comment by mhutch** [comment]
@slluis are you building with xbuild then?

**Comment by slluis** [comment]
I'm not. Have you tried building with XS? Which version?

**Comment by mhutch** [comment]
@slluis 

on a master checkout, try:

```
git reset --hard && git clean -xdf && git pull
msbuild /t:Restore
msbuild
```

**Comment by mhutch** [comment]
@slluis I was able to build with my current MD checkout, which is my unified-refs branch, and was rebased onto master yesterday.

**Pull request merged**
