### PR TITLE
Add the ability to auto-import debug symbols

### PR DESCRIPTION
**Pull request by alanmcgovern**
We support searching for pdb files as well as mdb files.

### CODE REVIEW

**Comment by slluis** [comment]
This should be a packaging option (handled around here https://github.com/mono/mono-addins/blob/master/Mono.Addins.Setup/Mono.Addins.Setup/SetupTool.cs#L475), rather than an extension model option. That would more convenient for example if different build configurations need to produce different packages.

**Comment by alanmcgovern** [comment]
Is this approach more like what you'd want to see? If so i'll test it and finalize it!

**Comment by slluis** [comment]
Yes, that looks good.

**Comment by alanmcgovern** [comment]
This is ready to go now!

**Pull request merged**
