### PR TITLE
Upgrade csproj files to TargetFramework net4.5 and ToolsVersion 4.0

### PR DESCRIPTION
**Pull request by tpokorra**
this is another step to make Monodevelop compile with mono from git master

### CODE REVIEW

**Comment by slluis** [comment]
Why this change? Mono.Addins doesn't require .net 4.5.

**Comment by tpokorra** [comment]
I might be wrong, but as far as I understand, .net 2.0 and .net 4.0 have been removed from Mono git master? http://lists.ximian.com/pipermail/mono-devel-list/2014-October/042145.html

When using the latest mono from git master, I cannot compile MonoDevelop without these changes.

**Comment by jstedfast** [comment]
FWIW, I can still build monodevelop fine with Mono 3.12

**Comment by tpokorra** [comment]
yes, Mono 3.12 still supports .net 2.0 and 4.0, but not mono git master anymore.
I closed the pull request because I figured I was too early... and I should leave this to other people :)

**Pull request closed without merging**
