### PR TITLE
Fixes the bug described in issue #22.

### PR DESCRIPTION
**Pull request by diva**

### CODE REVIEW

**Comment by knocte** [comment]
@diva thanks for your patch! can you use tabs instead of space please?

**Comment by DamianSuess** [comment]
FYI for those unfamiliar with the defect:
#22 "Exception on list-update and update" - mautil.exe always crashes when looking for updates due to the use if ``addin.Addin.Id`` versus ``addin.Addin.LocalId``.

**Comment by mhutch** [comment]
I'm not sure LocalId is correct here, you probably need the namespace as well.

**Comment by mhutch** [comment]
cc @slluis

**Comment by slluis** [comment]
Yes, the namespace should be prepended.

**Comment by diva** [comment]
Hi @mhutch . Long time no see :)
I bumped into this again on my use of mautil, and now I really need this PR accepted, if possible. I fixed the tabs. Can you check?

**Comment by mhutch** [comment]
@slluis ^

**Pull request merged**
