### PR TITLE
[Addins] Add support for module dependencies without version checks.

### PR DESCRIPTION
**Pull request by Therzok**

### CODE REVIEW

**Comment by slluis** [comment]
I don't think this change is enough. Dependencies are checked at run-time.

**Comment by Therzok** [comment]
Well, this just removes the necessity of having a version specified.

**Comment by DamianSuess** [comment]
I see where youre going with this feature. Something such as this may benifit from a Mono.Addins configuration setting. It may work for one project/developer to remove Version, but not all

**Comment by Therzok** [comment]
This was fixed in another way in https://github.com/mono/mono-addins/commit/1919a2edc2cd4d85120062fec3b4b5f55cf6773e

**Pull request closed without merging**
