### PR TITLE
Embed Pdb and add SourceLink

### PR DESCRIPTION
**Pull request by KirillOsenkov**
Would be nice to have this, otherwise we can't debug into Mono.Addins:

image

### CODE REVIEW

**Review by Therzok — APPROVED** [review]

**Comment by KirillOsenkov** [comment]
@slluis when you get a chance, please

**Comment by Therzok** [comment]
@KirillOsenkov CI failed for some reason.

@slluis any chance this repo can be migrated to github actions?

**Comment by KirillOsenkov** [comment]
I looked and it seemed unrelated

**Comment by Therzok** [comment]
@slluis ping

**Comment by Therzok** [comment]
@slluis PTAL

**Comment by slluis** [comment]
I guess CI can't build from forks

**Comment by Therzok** [comment]
I'm going to merge this, it would be nice to be able to step into mono-addins.

**Pull request merged**
