### PR TITLE
fix 53827

### PR DESCRIPTION
**Pull request by Jammer77**
Keyboard accesse to FilterBox in AddIns Dialog implemented

### CODE REVIEW

**Comment by iainx** [comment]
This only works the first time you tab through all the widgets. Once the Notebook tabs are focused, the search bar can't be focused again with the keyboard

**Comment by iainx** [comment]
It might be easiest to create a subclass of GtkNotebook that handles adding the search bar in the correct place, and has a custom OnFocused override.

**Comment by iainx** [comment]
This is a clever fix, but could it be done by just pinvoking gtk_notebook_set_action_widget because our Gtk# doesn't seem to bind it?

**Comment by Therzok** [comment]
(It's an API new in gtk# 2.24, we use 2.24 as native lib but bind 2.12)

**Pull request merged**
